"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type LanguageCode = "en" | "es" | "tr" | "pt" | "ar" | "fr" | "de" | "it" | "ru" | "zh" | "hi" | "ja" | "ko"

interface LanguageContextType {
  language: LanguageCode
  setLanguage: (lang: LanguageCode) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    "header.home": "Home",
    "header.about": "About",
    "header.contact": "Contact",
    "header.faq": "FAQ",
    "header.login": "Login",
    "header.register": "Register",
    "hero.title": "Invest in Your Future with Confidence",
    "hero.subtitle":
      "Join thousands of investors who are growing their wealth through our secure, transparent, and professional investment platform.",
    "hero.getStarted": "Get Started",
    "hero.learnMore": "Learn More",
    "hero.aum": "Assets Under Management",
    "hero.investors": "Active Investors",
    "hero.support": "Platform Support",
    "chart.title": "Trading Chart",
    "chart.subtitle": "Real-time market analysis and price trends",
    "market.title": "Cryptocurrency Market",
    "market.subtitle": "Track the top 20 cryptocurrencies in real-time",
    "market.search": "Search cryptocurrencies...",
    "market.name": "Name",
    "market.price": "Price",
    "market.change": "24h Change",
    "market.marketCap": "Market Cap",
    "plans.title": "Choose Your Investment Plan",
    "plans.subtitle": "Select the plan that best fits your investment goals and financial strategy",
    "plans.popular": "Most Popular",
    "plans.investNow": "Invest Now",
    "footer.quickLinks": "Quick Links",
    "footer.support": "Support",
    "footer.followUs": "Follow Us",
    "footer.email": "Email",
    "footer.phone": "Phone",
    "footer.office": "Office",
    "footer.copyright": "Copyright 2025 TrustXchange247. All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
  },
  es: {
    "header.home": "Inicio",
    "header.about": "Acerca de",
    "header.contact": "Contacto",
    "header.faq": "Preguntas Frecuentes",
    "header.login": "Iniciar Sesión",
    "header.register": "Registrarse",
    "hero.title": "Invierte en tu Futuro con Confianza",
    "hero.subtitle":
      "Únete a miles de inversores que están aumentando su riqueza a través de nuestra plataforma de inversión segura, transparente y profesional.",
    "hero.getStarted": "Comenzar",
    "hero.learnMore": "Aprender Más",
    "hero.aum": "Activos Bajo Administración",
    "hero.investors": "Inversores Activos",
    "hero.support": "Soporte de Plataforma",
    "chart.title": "Gráfico de Operaciones",
    "chart.subtitle": "Análisis de mercado en tiempo real y tendencias de precios",
    "market.title": "Mercado de Criptomonedas",
    "market.subtitle": "Sigue las 20 principales criptomonedas en tiempo real",
    "market.search": "Buscar criptomonedas...",
    "market.name": "Nombre",
    "market.price": "Precio",
    "market.change": "Cambio 24h",
    "market.marketCap": "Capitalización de Mercado",
    "plans.title": "Elige tu Plan de Inversión",
    "plans.subtitle": "Selecciona el plan que mejor se adapte a tus objetivos de inversión y estrategia financiera",
    "plans.popular": "Más Popular",
    "plans.investNow": "Invertir Ahora",
    "footer.quickLinks": "Enlaces Rápidos",
    "footer.support": "Soporte",
    "footer.followUs": "Síguenos",
    "footer.email": "Correo Electrónico",
    "footer.phone": "Teléfono",
    "footer.office": "Oficina",
    "footer.copyright": "Derechos de autor 2025 TrustXchange247. Todos los derechos reservados.",
    "footer.privacy": "Política de Privacidad",
    "footer.terms": "Términos de Servicio",
  },
  tr: {
    "header.home": "Ana Sayfa",
    "header.about": "Hakkında",
    "header.contact": "İletişim",
    "header.faq": "Sıkça Sorulan Sorular",
    "header.login": "Giriş Yap",
    "header.register": "Kayıt Ol",
    "hero.title": "Güvenle Geleceğine Yatırım Yap",
    "hero.subtitle":
      "Güvenli, şeffaf ve profesyonel yatırım platformumuz aracılığıyla servetlerini artıran binlerce yatırımcının yanına katıl.",
    "hero.getStarted": "Başla",
    "hero.learnMore": "Daha Fazla Bilgi",
    "hero.aum": "Yönetim Altındaki Varlıklar",
    "hero.investors": "Aktif Yatırımcılar",
    "hero.support": "Platform Desteği",
    "chart.title": "İşlem Grafiği",
    "chart.subtitle": "Gerçek zamanlı pazar analizi ve fiyat eğilimleri",
    "market.title": "Kripto Para Pazarı",
    "market.subtitle": "En iyi 20 kripto parayı gerçek zamanlı olarak takip edin",
    "market.search": "Kripto paraları ara...",
    "market.name": "Ad",
    "market.price": "Fiyat",
    "market.change": "24s Değişim",
    "market.marketCap": "Pazar Değeri",
    "plans.title": "Yatırım Planınızı Seçin",
    "plans.subtitle": "Yatırım hedeflerinize ve finansal stratejinize en uygun planı seçin",
    "plans.popular": "En Popüler",
    "plans.investNow": "Şimdi Yatırım Yap",
    "footer.quickLinks": "Hızlı Bağlantılar",
    "footer.support": "Destek",
    "footer.followUs": "Bizi Takip Edin",
    "footer.email": "E-posta",
    "footer.phone": "Telefon",
    "footer.office": "Ofis",
    "footer.copyright": "Telif Hakkı 2025 TrustXchange247. Tüm hakları saklıdır.",
    "footer.privacy": "Gizlilik Politikası",
    "footer.terms": "Hizmet Şartları",
  },
  pt: {
    "header.home": "Início",
    "header.about": "Sobre",
    "header.contact": "Contato",
    "header.faq": "Perguntas Frequentes",
    "header.login": "Entrar",
    "header.register": "Registrar",
    "hero.title": "Invista no Seu Futuro com Confiança",
    "hero.subtitle":
      "Junte-se a milhares de investidores que estão aumentando sua riqueza através da nossa plataforma de investimento segura, transparente e profissional.",
    "hero.getStarted": "Começar",
    "hero.learnMore": "Saiba Mais",
    "hero.aum": "Ativos Sob Gestão",
    "hero.investors": "Investidores Ativos",
    "hero.support": "Suporte da Plataforma",
    "chart.title": "Gráfico de Negociação",
    "chart.subtitle": "Análise de mercado em tempo real e tendências de preços",
    "market.title": "Mercado de Criptomoedas",
    "market.subtitle": "Acompanhe as 20 principais criptomoedas em tempo real",
    "market.search": "Procure criptomoedas...",
    "market.name": "Nome",
    "market.price": "Preço",
    "market.change": "Mudança 24h",
    "market.marketCap": "Capitalização de Mercado",
    "plans.title": "Escolha Seu Plano de Investimento",
    "plans.subtitle":
      "Selecione o plano que melhor se adequa aos seus objetivos de investimento e estratégia financeira",
    "plans.popular": "Mais Popular",
    "plans.investNow": "Investir Agora",
    "footer.quickLinks": "Links Rápidos",
    "footer.support": "Suporte",
    "footer.followUs": "Nos Siga",
    "footer.email": "E-mail",
    "footer.phone": "Telefone",
    "footer.office": "Escritório",
    "footer.copyright": "Direitos autorais 2025 TrustXchange247. Todos os direitos reservados.",
    "footer.privacy": "Política de Privacidade",
    "footer.terms": "Termos de Serviço",
  },
  ar: {
    "header.home": "الصفحة الرئيسية",
    "header.about": "حول",
    "header.contact": "اتصل",
    "header.faq": "الأسئلة الشائعة",
    "header.login": "تسجيل الدخول",
    "header.register": "قيد",
    "hero.title": "استثمر في مستقبلك بثقة",
    "hero.subtitle":
      "انضم إلى آلاف المستثمرين الذين يزيدون من ثروتهم من خلال منصة الاستثمار الآمنة والشفافة والاحترافية الخاصة بنا.",
    "hero.getStarted": "ابدأ",
    "hero.learnMore": "معرفة المزيد",
    "hero.aum": "الأصول المدارة",
    "hero.investors": "المستثمرون النشطون",
    "hero.support": "دعم المنصة",
    "chart.title": "مخطط التداول",
    "chart.subtitle": "تحليل السوق في الوقت الفعلي واتجاهات الأسعار",
    "market.title": "سوق العملات المشفرة",
    "market.subtitle": "تابع أفضل 20 عملة مشفرة في الوقت الفعلي",
    "market.search": "البحث عن العملات المشفرة...",
    "market.name": "الاسم",
    "market.price": "السعر",
    "market.change": "التغيير 24 ساعة",
    "market.marketCap": "القيمة السوقية",
    "plans.title": "اختر خطة الاستثمار الخاصة بك",
    "plans.subtitle": "حدد الخطة التي تناسب أهداف الاستثمار الخاصة بك وإستراتيج itkمة المالية",
    "plans.popular": "الأكثر شيوعا",
    "plans.investNow": "استثمر الآن",
    "footer.quickLinks": "روابط سريعة",
    "footer.support": "الدعم",
    "footer.followUs": "تابعنا",
    "footer.email": "بريد إلكتروني",
    "footer.phone": "هاتف",
    "footer.office": "مكتب",
    "footer.copyright": "حقوق الطبع والنشر 2025 TrustXchange247. كل الحقوق محفوظة.",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",
  },
  fr: {
    "header.home": "Accueil",
    "header.about": "À propos",
    "header.contact": "Contact",
    "header.faq": "FAQ",
    "header.login": "Connexion",
    "header.register": "Inscription",
    "hero.title": "Investissez dans Votre Avenir en Confiance",
    "hero.subtitle":
      "Rejoignez des milliers d'investisseurs qui font fructifier leur patrimoine grâce à notre plateforme d'investissement sécurisée, transparente et professionnelle.",
    "hero.getStarted": "Commencer",
    "hero.learnMore": "En Savoir Plus",
    "hero.aum": "Actifs Gérés",
    "hero.investors": "Investisseurs Actifs",
    "hero.support": "Support Plateforme",
    "chart.title": "Graphique de Trading",
    "chart.subtitle": "Analyse de marché en temps réel et tendances des prix",
    "market.title": "Marché des Cryptomonnaies",
    "market.subtitle": "Suivez les 20 principales cryptomonnaies en temps réel",
    "market.search": "Rechercher des cryptomonnaies...",
    "market.name": "Nom",
    "market.price": "Prix",
    "market.change": "Changement 24h",
    "market.marketCap": "Capitalisation Boursière",
    "plans.title": "Choisissez Votre Plan d'Investissement",
    "plans.subtitle":
      "Sélectionnez le plan qui convient le mieux à vos objectifs d'investissement et à votre stratégie financière",
    "plans.popular": "Plus Populaire",
    "plans.investNow": "Investir Maintenant",
    "footer.quickLinks": "Liens Rapides",
    "footer.support": "Support",
    "footer.followUs": "Suivez-nous",
    "footer.email": "Email",
    "footer.phone": "Téléphone",
    "footer.office": "Bureau",
    "footer.copyright": "Droits d'auteur 2025 TrustXchange247. Tous droits réservés.",
    "footer.privacy": "Politique de Confidentialité",
    "footer.terms": "Conditions de Service",
  },
  de: {
    "header.home": "Startseite",
    "header.about": "Über uns",
    "header.contact": "Kontakt",
    "header.faq": "Häufig gestellte Fragen",
    "header.login": "Anmelden",
    "header.register": "Registrieren",
    "hero.title": "Investieren Sie mit Zuversicht in Ihre Zukunft",
    "hero.subtitle":
      "Schließen Sie sich Tausenden von Anlegern an, die ihr Vermögen über unsere sichere, transparente und professionelle Anlageplattform vermehren.",
    "hero.getStarted": "Anfangen",
    "hero.learnMore": "Mehr Erfahren",
    "hero.aum": "Verwaltete Vermögenswerte",
    "hero.investors": "Aktive Investoren",
    "hero.support": "Plattform-Unterstützung",
    "chart.title": "Handelschart",
    "chart.subtitle": "Echtzeitmarktanalyse und Kurstrends",
    "market.title": "Kryptowährungsmarkt",
    "market.subtitle": "Verfolgen Sie die Top 20 Kryptowährungen in Echtzeit",
    "market.search": "Kryptowährungen durchsuchen...",
    "market.name": "Name",
    "market.price": "Preis",
    "market.change": "24-Stunden-Änderung",
    "market.marketCap": "Marktkapitalisierung",
    "plans.title": "Wählen Sie Ihren Investitionsplan",
    "plans.subtitle": "Wählen Sie den Plan, der am besten zu Ihren Anlagezielen und Ihrer Finanzstrategie passt",
    "plans.popular": "Am Beliebtesten",
    "plans.investNow": "Jetzt Investieren",
    "footer.quickLinks": "Schnelllinks",
    "footer.support": "Unterstützung",
    "footer.followUs": "Folgen Sie uns",
    "footer.email": "E-Mail",
    "footer.phone": "Telefon",
    "footer.office": "Büro",
    "footer.copyright": "Urheberrecht 2025 TrustXchange247. Alle Rechte vorbehalten.",
    "footer.privacy": "Datenschutzrichtlinie",
    "footer.terms": "Servicebestimmungen",
  },
  it: {
    "header.home": "Home",
    "header.about": "Chi Siamo",
    "header.contact": "Contatti",
    "header.faq": "Domande Frequenti",
    "header.login": "Accedi",
    "header.register": "Registrati",
    "hero.title": "Investi nel Tuo Futuro con Fiducia",
    "hero.subtitle":
      "Unisciti a migliaia di investitori che stanno facendo crescere il loro patrimonio attraverso la nostra piattaforma di investimento sicura, trasparente e professionale.",
    "hero.getStarted": "Inizia",
    "hero.learnMore": "Scopri di Più",
    "hero.aum": "Patrimonio Gestito",
    "hero.investors": "Investitori Attivi",
    "hero.support": "Supporto della Piattaforma",
    "chart.title": "Grafico di Trading",
    "chart.subtitle": "Analisi di mercato in tempo reale e tendenze dei prezzi",
    "market.title": "Mercato delle Criptovalute",
    "market.subtitle": "Monitora le top 20 criptovalute in tempo reale",
    "market.search": "Cerca criptovalute...",
    "market.name": "Nome",
    "market.price": "Prezzo",
    "market.change": "Variazione 24h",
    "market.marketCap": "Capitalizzazione di Mercato",
    "plans.title": "Scegli il Tuo Piano di Investimento",
    "plans.subtitle":
      "Seleziona il piano più adatto ai tuoi obiettivi di investimento e alla tua strategia finanziaria",
    "plans.popular": "Più Popolare",
    "plans.investNow": "Investi Ora",
    "footer.quickLinks": "Collegamenti Veloci",
    "footer.support": "Supporto",
    "footer.followUs": "Seguici",
    "footer.email": "Email",
    "footer.phone": "Telefono",
    "footer.office": "Ufficio",
    "footer.copyright": "Copyright 2025 TrustXchange247. Tutti i diritti riservati.",
    "footer.privacy": "Politica sulla Privacy",
    "footer.terms": "Termini di Servizio",
  },
  ru: {
    "header.home": "Главная",
    "header.about": "О нас",
    "header.contact": "Контакты",
    "header.faq": "Часто задаваемые вопросы",
    "header.login": "Вход",
    "header.register": "Регистрация",
    "hero.title": "Инвестируйте в Свое Будущее с Уверенностью",
    "hero.subtitle":
      "Присоединяйтесь к тысячам инвесторов, которые увеличивают свое богатство через нашу безопасную, прозрачную и профессиональную инвестиционную платформу.",
    "hero.getStarted": "Начать",
    "hero.learnMore": "Узнать Больше",
    "hero.aum": "Управляемые Активы",
    "hero.investors": "Активные Инвесторы",
    "hero.support": "Поддержка Платформы",
    "chart.title": "График Торговли",
    "chart.subtitle": "Анализ рынка в реальном времени и тенденции цен",
    "market.title": "Рынок Криптовалют",
    "market.subtitle": "Отслеживайте топ-20 криптовалют в реальном времени",
    "market.search": "Поиск криптовалют...",
    "market.name": "Название",
    "market.price": "Цена",
    "market.change": "Изменение 24ч",
    "market.marketCap": "Рыночная Капитализация",
    "plans.title": "Выберите Свой Инвестиционный План",
    "plans.subtitle":
      "Выберите план, который лучше всего соответствует вашим инвестиционным целям и финансовой стратегии",
    "plans.popular": "Самый Популярный",
    "plans.investNow": "Инвестировать Сейчас",
    "footer.quickLinks": "Быстрые Ссылки",
    "footer.support": "Поддержка",
    "footer.followUs": "Следите за Нами",
    "footer.email": "Электронная Почта",
    "footer.phone": "Телефон",
    "footer.office": "Офис",
    "footer.copyright": "Авторские права 2025 TrustXchange247. Все права защищены.",
    "footer.privacy": "Политика Конфиденциальности",
    "footer.terms": "Условия Обслуживания",
  },
  zh: {
    "header.home": "首页",
    "header.about": "关于",
    "header.contact": "联系",
    "header.faq": "常见问题",
    "header.login": "登录",
    "header.register": "注册",
    "hero.title": "充满信心地投资你的未来",
    "hero.subtitle": "加入数千名通过我们安全、透明和专业的投资平台增加财富的投资者。",
    "hero.getStarted": "开始",
    "hero.learnMore": "了解更多",
    "hero.aum": "管理资产",
    "hero.investors": "活跃投资者",
    "hero.support": "平台支持",
    "chart.title": "交易图表",
    "chart.subtitle": "实时市场分析和价格趋势",
    "market.title": "加密货币市场",
    "market.subtitle": "实时追踪排名前20的加密货币",
    "market.search": "搜索加密货币...",
    "market.name": "名称",
    "market.price": "价格",
    "market.change": "24小时变化",
    "market.marketCap": "市场资本化",
    "plans.title": "选择您的投资计划",
    "plans.subtitle": "选择最适合您的投资目标和财务策略的计划",
    "plans.popular": "最受欢迎",
    "plans.investNow": "现在投资",
    "footer.quickLinks": "快速链接",
    "footer.support": "支持",
    "footer.followUs": "关注我们",
    "footer.email": "电子邮件",
    "footer.phone": "电话",
    "footer.office": "办公室",
    "footer.copyright": "版权所有 2025 TrustXchange247。保留所有权利。",
    "footer.privacy": "隐私政策",
    "footer.terms": "服务条款",
  },
  hi: {
    "header.home": "होम",
    "header.about": "हमारे बारे में",
    "header.contact": "संपर्क",
    "header.faq": "अक्सर पूछे जाने वाले प्रश्न",
    "header.login": "लॉगिन",
    "header.register": "पंजीकरण",
    "hero.title": "आत्मविश्वास के साथ अपने भविष्य में निवेश करें",
    "hero.subtitle": "हजारों निवेशकों के साथ जुड़ें जो हमारे सुरक्षित, पारदर्शी और पेशेवर निवेश मंच के माध्यम से अपनी संपत्ति बढ़ा रहे हैं।",
    "hero.getStarted": "शुरू करें",
    "hero.learnMore": "अधिक जानें",
    "hero.aum": "प्रबंधित संपत्ति",
    "hero.investors": "सक्रिय निवेशक",
    "hero.support": "मंच समर्थन",
    "chart.title": "ट्रेडिंग चार्ट",
    "chart.subtitle": "वास्तविक समय बाजार विश्लेषण और मूल्य प्रवृत्तियां",
    "market.title": "क्रिप्टोकरेंसी बाजार",
    "market.subtitle": "शीर्ष 20 क्रिप्टोकरेंसी को वास्तविक समय में ट्रैक करें",
    "market.search": "क्रिप्टोकरेंसी खोजें...",
    "market.name": "नाम",
    "market.price": "मूल्य",
    "market.change": "24h परिवर्तन",
    "market.marketCap": "बाजार पूंजीकरण",
    "plans.title": "अपनी निवेश योजना चुनें",
    "plans.subtitle": "वह योजना चुनें जो आपके निवेश लक्ष्यों और वित्तीय रणनीति के लिए सबसे उपयुक्त हो",
    "plans.popular": "सबसे लोकप्रिय",
    "plans.investNow": "अभी निवेश करें",
    "footer.quickLinks": "त्वरित लिंक",
    "footer.support": "समर्थन",
    "footer.followUs": "हमें फॉलो करें",
    "footer.email": "ईमेल",
    "footer.phone": "फोन",
    "footer.office": "कार्यालय",
    "footer.copyright": "कॉपीराइट 2025 TrustXchange247। सर्वाधिकार सुरक्षित।",
    "footer.privacy": "गोपनीयता नीति",
    "footer.terms": "सेवा की शर्तें",
  },
  ja: {
    "header.home": "ホーム",
    "header.about": "について",
    "header.contact": "お問い合わせ",
    "header.faq": "よくある質問",
    "header.login": "ログイン",
    "header.register": "登録",
    "hero.title": "自信を持ってあなたの未来に投資する",
    "hero.subtitle":
      "当社の安全で透明性があり、専門的な投資プラットフォームを通じて富を増やしている何千もの投資家に参加してください。",
    "hero.getStarted": "始める",
    "hero.learnMore": "詳細を見る",
    "hero.aum": "運用資産",
    "hero.investors": "アクティブな投資家",
    "hero.support": "プラットフォームサポート",
    "chart.title": "トレーディングチャート",
    "chart.subtitle": "リアルタイム市場分析と価格トレンド",
    "market.title": "暗号通貨市場",
    "market.subtitle": "トップ20の暗号通貨をリアルタイムで追跡",
    "market.search": "暗号通貨を検索...",
    "market.name": "名前",
    "market.price": "価格",
    "market.change": "24時間変化",
    "market.marketCap": "時価総額",
    "plans.title": "投資プランを選択してください",
    "plans.subtitle": "投資目標と財務戦略に最適なプランを選択してください",
    "plans.popular": "最も人気",
    "plans.investNow": "今すぐ投資",
    "footer.quickLinks": "クイックリンク",
    "footer.support": "サポート",
    "footer.followUs": "フォローする",
    "footer.email": "メール",
    "footer.phone": "電話",
    "footer.office": "オフィス",
    "footer.copyright": "著作権2025 TrustXchange247。著作権所有。",
    "footer.privacy": "プライバシーポリシー",
    "footer.terms": "利用規約",
  },
  ko: {
    "header.home": "홈",
    "header.about": "소개",
    "header.contact": "연락처",
    "header.faq": "자주 묻는 질문",
    "header.login": "로그인",
    "header.register": "가입",
    "hero.title": "자신감 있게 당신의 미래에 투자하세요",
    "hero.subtitle":
      "안전하고 투명하며 전문적인 투자 플랫폼을 통해 부를 늘리고 있는 수천 명의 투자자들에게 참여하세요.",
    "hero.getStarted": "시작하기",
    "hero.learnMore": "더 알아보기",
    "hero.aum": "관리 자산",
    "hero.investors": "활성 투자자",
    "hero.support": "플랫폼 지원",
    "chart.title": "거래 차트",
    "chart.subtitle": "실시간 시장 분석 및 가격 추세",
    "market.title": "암호화폐 시장",
    "market.subtitle": "상위 20개 암호화폐를 실시간으로 추적하세요",
    "market.search": "암호화폐 검색...",
    "market.name": "이름",
    "market.price": "가격",
    "market.change": "24시간 변화",
    "market.marketCap": "시가총액",
    "plans.title": "투자 계획을 선택하세요",
    "plans.subtitle": "투자 목표 및 재무 전략에 가장 적합한 계획을 선택하세요",
    "plans.popular": "가장 인기 있는",
    "plans.investNow": "지금 투자하세요",
    "footer.quickLinks": "빠른 링크",
    "footer.support": "지원",
    "footer.followUs": "팔로우하기",
    "footer.email": "이메일",
    "footer.phone": "전화",
    "footer.office": "사무실",
    "footer.copyright": "저작권 2025 TrustXchange247. 모든 권리 보유.",
    "footer.privacy": "개인정보 보호정책",
    "footer.terms": "서비스 약관",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>("en")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as LanguageCode | null
    if (savedLanguage && translations[savedLanguage]) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    return translations[language]?.[key] ?? key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
